// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP2VySwh0SAC19usxuQQeycts4E-Pm2lk',
    appId: '1:415627597609:web:4ac965fbc7eb530ec8c938',
    messagingSenderId: '415627597609',
    projectId: 'dreamtact',
    authDomain: 'dreamtact.firebaseapp.com',
    storageBucket: 'dreamtact.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEQTMLVSF3LqhoWlcjlusYJF2jIXY7-o8',
    appId: '1:415627597609:android:53223d6ae489fd03c8c938',
    messagingSenderId: '415627597609',
    projectId: 'dreamtact',
    storageBucket: 'dreamtact.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATwU0fjTrdnsAIZwFPyPnECZgpyekdMb4',
    appId: '1:415627597609:ios:82cf27a69aa6cc09c8c938',
    messagingSenderId: '415627597609',
    projectId: 'dreamtact',
    storageBucket: 'dreamtact.appspot.com',
    iosBundleId: 'com.example.appDreamtact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATwU0fjTrdnsAIZwFPyPnECZgpyekdMb4',
    appId: '1:415627597609:ios:82cf27a69aa6cc09c8c938',
    messagingSenderId: '415627597609',
    projectId: 'dreamtact',
    storageBucket: 'dreamtact.appspot.com',
    iosBundleId: 'com.example.appDreamtact',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP2VySwh0SAC19usxuQQeycts4E-Pm2lk',
    appId: '1:415627597609:web:ee2a8f0329f58939c8c938',
    messagingSenderId: '415627597609',
    projectId: 'dreamtact',
    authDomain: 'dreamtact.firebaseapp.com',
    storageBucket: 'dreamtact.appspot.com',
  );

}